### ISSUE TITLE
Modify config object; `topic-exchange-name` should not be apart of the connection config

### ISSUE THREAD

**Issue by jpzk** [SpinGo/op-rabbit#18]
My application.conf is the current working directory, in the same place where the Jar is placed. If I want to add the configuration manually with the ConfigFactor like below. The rabbitmq.topic-exchange-name will not be used, instead, it is set as a lazy val in RabbitControl.scala:18. See source code below:

```
val config = ConfigFactory.parseFile(new File("application.conf")).getConfig("rabbitmq")
val rabbitMq = actorSystem.actorOf(Props(new RabbitControl(ConnectionParams.fromConfig(config))))


rabbitmq {
  topic-exchange-name = "name"
  connection-timeout = 3000
  virtual-host = "/"
  hosts = ["rabbit.test.com"]
  username = "user"
  password = "pass"
  port = 5672
  timeout = 3s
}

[info] Running RabbitTest 
[info] [ERROR] [07/31/2015 14:50:47.636] [such-system-akka.actor.default-dispatcher-3]         [akka://such-system/user/$a] No configuration setting found for key 'rabbitmq.topic-exchange-name'
[info] com.typesafe.config.ConfigException$Missing: No configuration setting found for key     'rabbitmq.topic-exchange-name'
[info]  at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
[info]  at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
[info]  at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
[info]  at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
[info]  at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
[info]  at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
[info]  at com.spingo.op_rabbit.RabbitControl$.topicExchangeName$lzycompute(RabbitControl.
```

**Comment by timcharper** [comment]
I recommend specifying the config-file to use via the JVM property, "config.file", such as:

```
java -jar  -Dconfig.file=/path/to//application.conf ...
```

Also, your issue brings my focus to an important point, that perhaps connection parameters have no business being mixed in with `op-rabbit` parameters. I'm considering changing the configuration structure to this:

``` conf
op-rabbit {
  topic-exchange-name = "name"
  connection {
    connection-timeout = 3000
    virtual-host = "/"
    hosts = ["rabbit.test.com"]
    username = "user"
    password = "pass"
    port = 5672
    timeout = 3s
  }
}
```

Allowing the topicExchangeName to be injected in by the application, and not via a parameter, adds complexity, as the default is being pulled in `TopicMessage.apply`.

**Comment by timcharper** [comment]
Completed in 32f552cac45b731f3db688034304e9c7cc74e81e
