### ISSUE TITLE
No retry on Exception message: Socket closed

### ISSUE THREAD

**Issue by sanjaykatla** [SpinGo/op-rabbit#199]
[ERROR] [08/25/2023 00:47:31.460] [appName-op-rabbit.default-channel-dispatcher-5] [akka://appName/user/$b/confirmed-publisher] Publisher channel was disconnected unexpectedly
com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:916)
	at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:906)
	at com.rabbitmq.client.impl.AMQConnection.handleConnectionClose(AMQConnection.java:844)
	at com.rabbitmq.client.impl.AMQConnection.processControlCommand(AMQConnection.java:799)
	at com.rabbitmq.client.impl.AMQConnection$1.processAsync(AMQConnection.java:242)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:650)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:597)
	at java.lang.Thread.run(Thread.java:750)

[WARN] [08/25/2023 00:47:31.466] [app-synce-thread-4] [akka://appName/user/$b/connection] akka://appName/user/$b/connection lost connection to amqp://user@{rabbit-dns:5672}:5672//

[WARN] [08/25/2023 00:47:31.469] [app-synce-thread-7] [akka://appName/user/$b/connection/confirmed-publisher-channel] akka://appName/user/$b/connection/confirmed-publisher-channel disconnected

00:47:36 [AMQP Connection 172.18.108.174:5672] WARN  com.rabbitmq.client.impl.ForgivingExceptionHandler [] - An unexpected connection driver error occured **(Exception message: Socket closed)**
[WARN] [08/25/2023 00:47:36.476] [app-synce-thread-4] [akka://appName/user/$b/connection] null

It doesn't retry after this. All newly published message are all lost.

**Comment by sanjaykatla** [comment]
It reconnects when we get connection error instead of **Socked Closed**

[ERROR] [08/25/2023 00:47:31.460] [appName-op-rabbit.default-channel-dispatcher-7] [akka://appName/user/$a/confirmed-publisher] Publisher channel was disconnected unexpectedly
com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:916)
	at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:906)
	at com.rabbitmq.client.impl.AMQConnection.handleConnectionClose(AMQConnection.java:844)
	at com.rabbitmq.client.impl.AMQConnection.processControlCommand(AMQConnection.java:799)
	at com.rabbitmq.client.impl.AMQConnection$1.processAsync(AMQConnection.java:242)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:650)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:597)
	at java.lang.Thread.run(Thread.java:750)

[WARN] [08/25/2023 00:47:31.466] [app-synce-thread-6] [akka://appName/user/$a/connection] akka://appName/user/$a/connection lost connection to amqp://user@{rabbit-dns:5672}:5672//


[WARN] [08/25/2023 00:47:31.469] [appName-op-rabbit.default-channel-dispatcher-5] [akka://appName/user/$a/connection/$a] akka://appName/user/$a/connection/$a disconnected
[WARN] [08/25/2023 00:47:31.469] [app-synce-thread-0] [akka://appName/user/$a/connection/confirmed-publisher-channel] akka://appName/user/$a/connection/confirmed-publisher-channel disconnected
[WARN] [08/25/2023 00:47:31.469] [appName-op-rabbit.default-channel-dispatcher-3] [akka://appName/user/$c/connection/$a] akka://appName/user/$c/connection/$a disconnected
[WARN] [08/25/2023 00:47:31.469] [appName-op-rabbit.default-channel-dispatcher-3] [akka://appName/user/$c/connection/$a] akka://appName/user/$c/connection/$a disconnected

[INFO] [08/25/2023 00:47:31.481] [appName-op-rabbit.default-channel-dispatcher-7] [akka://appName/user/$a/connection/$a] akka://appName/user/$a/connection/$a connected
