### ISSUE TITLE
Error with AkkaStreams

### ISSUE THREAD

**Issue by Ciaran0** [SpinGo/op-rabbit#69]
Im getting this error when running OP-Rabbit in an Akka-HTTP project.
Im not sure what the issue is.

`[error] (run-main-0) java.lang.ClassCastException: akka.NotUsed$ cannot be cast to scala.runtime.BoxedUnit
java.lang.ClassCastException: akka.NotUsed$ cannot be cast to scala.runtime.BoxedUnit
    at com.spingo.op_rabbit.stream.RabbitSource$$anonfun$apply$7.apply(RabbitSource.scala:167)
    at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:679)
    at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:678)
    at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:678)
    at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:678)
    at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:678)
    at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:678)
    at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:665)
    at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:608)
    at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:189)
    at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:79)
    at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:343)
    at com.paddypower.streams.flows.BetStreamFlow.consumeBets(BetStreamFlow.scala:77)
    at com.paddypower.app.Boot$.delayedEndpoint$com$paddypower$app$Boot$1(Boot.scala:30)
    at com.paddypower.app.Boot$delayedInit$body.apply(Boot.scala:17)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at com.paddypower.app.Boot$.main(Boot.scala:17)
    at com.paddypower.app.Boot.main(Boot.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
`

Build.sbt
val akkaHttp = "2.4.2-RC2"  
    val opRabbitVersion = "1.2.1"  
    Seq(  
        "com.typesafe.akka" % "akka-http-experimental_2.11" % akkaHttp,  
        "com.typesafe.akka" % "akka-http-spray-json-experimental_2.11" % akkaHttp,  
        "org.scalatest" %% "scalatest" % "2.2.6" % "test",  
        "org.scalactic" %% "scalactic" % "2.2.6",
        "com.typesafe.akka" % "akka-http-testkit-experimental_2.11" % akkaHttp,
        "com.github.swagger-akka-http" %% "swagger-akka-http" % "0.6.2",
        "org.scala-lang" % "scala-reflect" % scalaVersion.value,
        "org.slf4j" % "slf4j-api" % "1.7.7",
        "ch.qos.logback"  %  "logback-classic"   % "1.1.3",
        "com.spingo" %% "op-rabbit-core"        % opRabbitVersion,
        "com.spingo" %% "op-rabbit-play-json"   % opRabbitVersion,
        "com.spingo" %% "op-rabbit-json4s"      % opRabbitVersion,
        "com.spingo" %% "op-rabbit-akka-stream-2-0" % opRabbitVersion,
        "com.spingo" %% "op-rabbit-spray-json" % opRabbitVersion,
        "com.websudos" %% "phantom-dsl" % "1.22.0",
        "com.websudos" %% "phantom-testkit" % "1.12.2" % "test, provided",
        "com.typesafe.akka" %% "akka-stream" % "2.4.2-RC2"
  )
Code:
val source = RabbitSource(
      rabbitControl,
      channel(qos = 3),
      consume(queue(
        "test-queue",
        durable = true,
        exclusive = false,
        autoDelete = false)),
      body(as[Car]))

val ackSink: AckedSink[Unit, Future[Unit]] = AckedSink.ack
val flow = source to ackSink
flow.run()

Do you have any idea why this might be happening?
Thanks

**Comment by Ciaran0** [comment]
Version issues.
